name: "create docker: envmid"
on:
  workflow_dispatch:
    inputs:
      arc:
        type: string
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          file: .export/cnf/xoxxox/docenv_envtry${{ inputs.arc }}.txt
          context: .export/cnf/xoxxox/docenv_envtry${{ inputs.arc }}
          push: true
          platforms: linux/amd64, linux/arm64
          tags: ghcr.io/cnnmmd/xoxxox/envtry:001${{ inputs.arc }}
